version: '3'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: angular-app
    container_name: angular-app
    ports:
      - 8080:80

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/dist/gui:/usr/share/nginx/html
    ports:
      - 80:80
