services:
  ldap-service:
    build:
      context: ../ldapService
      dockerfile: Dockerfile
      args:
        DOMAIN: ${USERDNSDOMAIN}
    image: ldap-service
    container_name: ldap-service
    ports:
      - 3000:3000
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${ENV}
    image: angular-app
    container_name: angular-app
    ports:
      - 80:80
      - 443:443